services:
  frontend:
    # image: example/gomongo
    build:
      dockerfile: ./Dockerfile
  mongodb:
    image: mongo:6-jammy
    ports:
      - '27017:27017'
    volumes:
      - dbdata6:/data/db
volumes:
  dbdata6: