apiVersion: v1
kind: Secret
metadata:
  name: "${DEPLOYMENT}-config"
  namespace: ${NS}
type: Opaque
data:
  DH_HOST: ZWMyLTU0LTE4Ny0xNTYtNTQudXMtd2VzdC0yLmNvbXB1dGUuYW1hem9uYXdzLmNvbQ==
  DB_NAME: aGVsbG9fd29ybGQ=
  DB_PORT: MjcwMTc=
  DB_PASS: ZHVkZQ==
  DB_USER: ZHVkZQ==